# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-08 14:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0004_auto_20160708_1640'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='expire_date',
            new_name='expiry_date',
        ),
    ]
