# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-08 16:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('public', '0005_auto_20160708_1736'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_bid', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('maximum_bid', models.DecimalField(decimal_places=2, default=0, max_digits=9, null=True)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('last_bid_date', models.DateTimeField()),
                ('is_smart_bid', models.BooleanField(default=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.Article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
